### ISSUE TITLE
attributes.owlOptions is required

### ISSUE THREAD

**Issue by dereklin** [jonahbron/angular-owl-carousel#1]
Hi,

Are you still developing this?  attributes.owlOptions is required.  It not passed in, the directive fails.

**Comment by jonahbron** [comment]
@dereklin I haven't worked on it since I finished the project I was using it for.  I'll be happy to merge pull-requests if you submit them.

**Comment by dereklin** [comment]
@jonahbron I haven't done pull-requests before.  This will be my first one :)  I hope I do it right.

**Comment by dereklin** [comment]
@jonahbron I landed on the Compare changes step, but can't create a new pull request...

**Comment by jonahbron** [comment]
@dereklin Are you comparing your repository to mine?  Are you comparing the right branches?

**Comment by fatuk** [comment]
@jonahbron  I added pull request that adds params in proper way. I plan to support this directive because I often use owl-carousel in my projects.

**Comment by jonahbron** [comment]
Pull-request merged.

**Comment by jonahbron** [comment]
@fatuk If you expect to support the directive, I'd be happy to release the Bower package name to you.  As you can see, I haven't touched this repository in a while.

**Comment by mikedizon** [comment]
@fatuk @dereklin @jonahbron where do you add in the options? I don't see it in the docs

**Comment by fatuk** [comment]
I'll write docs later. Actually I added the same options as on offsite of OwlCarousel2 http://www.owlcarousel.owlgraphic.com/docs/api-options.html

**Comment by mcblum** [comment]
@fatuk Do you add the options in the HTML or in the directive?
