### ISSUE TITLE
JSON.parse error because owl-options attribute required 

### ISSUE THREAD

**Issue by FranciZ** [jonahbron/angular-owl-carousel#12]
This is not documented in the example but the owl-options attribute is required or the `JSON.parse` fails on line `15`.

**Comment by itwasmattgregg** [comment]
@FranciZ how did you fix this?

**Comment by rickerd** [comment]
Use the master branch. There isn't a release / tag made that has the fix in it.
It has to do with JSON parse. You can put owl-options="{}" to quickfix the error. But no options will be passed to the directive since the object is empty.

**Comment by jonahbron** [comment]
@rickerd @FranciZ I made a new release from the master (v0.3.0), should fix your problem.  Thank @rickerd.
