### ISSUE TITLE
Working Example?

### ISSUE THREAD

**Issue by tonejac** [jonahbron/angular-owl-carousel#5]
Could you put together a working example of this code in the project? Or possibly a link to it working on Plunkr.co?

**Comment by ghost** [comment]
+1. I'm having trouble getting this to work. It seems like options need to be set but I can't seem to figure out how to set them. Are they meant to be set on the element e.g `<div owl-carousel="favouriteGames" items="4">` ? No matter what I try I end up getting a error TypeError: Cannot read property 'replace' of undefined in relation to not options being defined.
